### PR TITLE
Use Nix to install a custom build of Emacs on CI

### PR DESCRIPTION
**Pull request by akirak**
This PR is based on #13 but uses Nix to install Emacs with the tree-sitter parser for PHP.

You can also run the tests locally if you have Nix. First you have to add the following settings to `nix.conf` (`~/.config/nix/nix.conf` on Linux):

```
experimental-features = nix-command flakes
```

Then use the following command:

```
nix develop .#emacs-release-snapshot --accept-flake-config -c make test
```

You need `make` on your machine. Some users may not have one, so it would be better to add it to `buildInputs` in `flake.nix`:

```nix
  pkgs.mkShell {
    buildInputs = [
      pkgs.gnumake
      (emacsCIWith emacs)
    ];
  };
```

Note that `gnumake` may add some extra download time on CI.

### CODE REVIEW

**Comment by akirak** [comment]
@piotrkwiecinski Now the upstream `nix-emacs-ci` supports the customization required by this PR and [the test successfully runs](https://github.com/akirak/php-ts-mode/actions). Please feel free to merge the PR, tweak the configuration to your preference, or use it as an example.

**Comment by piotrkwiecinski** [comment]
@akirak thank you very much for help. It looks good. @zonuexe let's merge this one.

**Review by piotrkwiecinski — APPROVED** [review]

**Comment by akirak** [comment]
Also note, you have to update the dependencies periodically to test with the latest snapshot of Emacs, unlike `setup-emacs` action. You can run the following command periodically

```sh
nix flake update
```

or remove `flake.lock` from the repository to generate it every time on CI (it can add some execution time though).

**Comment by piotrkwiecinski** [comment]
Thank you for letting us know. I'll create an issue to track it. 
I'll try to create similar scheduled action to: https://github.com/purcell/nix-emacs-ci/blob/master/.github/workflows/update-snapshot.yml

**Comment by zonuexe** [comment]
@akirak @piotrkwiecinski Thank you.

**Pull request merged**
