### PR TITLE
Add indentation definitions

### PR DESCRIPTION
**Pull request by RedChops**
I've added a handful of indentation definitions here for most of the situations I've come across. In addition, I've removed "if_statement" because that only indented the leading parens of the conditional, not the conditions.

This list of indentations is opinionated and comes from the PSR12 style guidelines.

I also don't view this as a complete set. There are some situations where indenting doesn't work properly still, like when defining a function call chain like:

```
    $object->method1()
        ->method2();
```

The automatic indentation of method2 only takes place after the '->' symbol is fully typed out, since there doesn't seem to be an easy-to-use parent node in this situation.

### CODE REVIEW

**Comment by zonuexe** [comment]
@RedChops I was also looking into the indentation issue but couldn't solve it. Thank you very much!

**Comment by zonuexe** [comment]
@RedChops 
Have you ever submitted a copyright assignment to the Free Software Foundation?
If you haven't submitted yet, please read <https://orgmode.org/worg/org-contribute.html#copyright> and email the FSF.

Thank you for your cooperation!

**Comment by RedChops** [comment]
@zonuexe 
I have just submitted a copyright assignment to FSF this morning, I'll get it signed as soon as I can.
Thanks!

**Comment by RedChops** [comment]
@zonuexe 
I have received my executed copyright assignment from the FSF. Do you need anything else in this regard from me?

**Pull request merged**
